#
# Coordinate the AWS CodeBuild steps for a multi-arch Docker image.
#
version: 0.2

batch:
    fast-fail: true
    build-graph:
        - identifier: arm64v8
          buildspec: CodeBuild/buildspec-images.yml
          env:
            compute-type: BUILD_GENERAL1_SMALL
            image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
            privileged-mode: true
            variables:
              IMAGE_TAG: latest-arm64v8
        - identifier: amd64
          buildspec: CodeBuild/buildspec-images.yml
          env:
            compute-type: BUILD_GENERAL1_SMALL
            image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
            privileged-mode: true
            variables:
              IMAGE_TAG: latest-amd64
        - identifier: manifest
          buildspec: CodeBuild/buildspec-manifest.yml
          env:
            compute-type: BUILD_GENERAL1_SMALL
            image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
            privileged-mode: true
            depend-on:
                - arm64v8
                - amd64