#
# Build a Docker manifest list in AWS Codebuild.
#
version: 0.2

batch:
    fast-fail: true
    build-graph:
        - identifier: arm64v8
          buildspec: buildspec-images.yml
          compute-type: BUILD_GENERAL1_SMALL
          image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
          variables:
            IMAGE_TAG: latest-arm64v8
        - identifier: amd64
          buildspec: buildspec-images.yml
          compute-type: BUILD_GENERAL1_SMALL
          image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
          variables:
            IMAGE_TAG: latest-amd64
        - identifier: manifest
          depend-on:
              - arm64v8
              - amd64

phases:
    pre_build:
        commands:
            - set -euo pipefail
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - set -euo pipefail
            - echo Build started on `date`
            - echo Building the Docker manifest...
            - export DOCKER_CLI_EXPERIMENTAL=enabled
            - docker manifest create $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest-arm64v8 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest-amd64
            - docker manifest annotate --arch arm64 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest-arm64v8
            - docker manifest annotate --arch amd64 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest-amd64

    post_build:
        commands:
            - set -euo pipefail
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker manifest push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
            - docker manifest inspect $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME