#
# Build ARM and Intel Docker images in AWS Codebuild.
#
version: 0.2

batch:
    build-list:
        - identifier: arm64v8
          compute-type: BUILD_GENERAL1_SMALL
          image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
          variables:
            IMAGE_TAG: latest-arm64v8
        - identifier: amd64
          compute-type: BUILD_GENERAL1_SMALL
          image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
          variables:
            IMAGE_TAG: latest-amd64

phases:
    pre_build:
        commands:
            - set -euo pipefail
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - set -euo pipefail
            - echo Build started on `date`
            - echo Building the Docker image...
            - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    post_build:
        commands:
            - set -euo pipefail
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG