version: 2

models:
  - name: casos
    description: >
      The Puerto Rico Department of Health's daily COVID-19 cases datasets.
      We make one (or more) download per day and keep them all, as tracked
      by the `downloaded_at` column.  The dataset is one record per case.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
      - name: class
        description: >
          What type of case this record represents, "confirmed" or "probable."
        tests:
          - not_null
          - accepted_values:
              values:
                - CONFIRMADO
                - PROBABLE
      - name: city
        description: >
          What municipality is recorded for the case.  Some official documentation
          suggests this is supposed to mean where the patient resides, but there
          has often been reason to suspect many cases might be recorded as the
          municipality of the test center they went to.
        tests:
          - not_null
          - relationships:
              to: ref('covid19datos_v2_casos_city_names')
              field: city
              where: >
                city NOT IN ('OTROS')
      - name: region
        description: >
          What region is recorded for the case.  Some official documentation
          suggests this is supposed to mean where the patient resides, but there
          has often been reason to suspect many cases might be recorded as the
          region of the test center they went to.
        tests:
          - not_null
          - relationships:
              to: ref('covid19datos_v2_casos_region_names')
              field: region
  - name: defunciones
    description: >
      The Puerto Rico Department of Health's daily COVID-19 deaths datasets.
      We make one (or more) download per day and keep them all, as tracked
      by the `downloaded_at` column.  The dataset is one record per death.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
      - name: co_region
        description: >
          What region is recorded for the death.
        tests:
          - relationships:
              to: ref('covid19datos_v2_casos_region_names')
              field: region
      - name: co_clasificacion
        description: >
          What type of death this record represents, "confirmed" or "probable."
        tests:
          - not_null
          - accepted_values:
              values:
                - CONFIRMADO
                - CONFIRMED
                - PROBABLE
      - name: fe_muerte
        description: Date of death.
        tests:
          - not_null
  - name: pruebas
    description: >
      The Puerto Rico Department of Health's daily COVID-19 tests datasets.
      We make one (or more) download per day and keep them all, as tracked
      by the `downloaded_at` column.  The dataset is one record per test.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
  - name: sistemas_salud
    description: >
      The Puerto Rico Department of Health's daily COVID-19 hospitals datasets.
      We make one (or more) download per day and keep them all, as tracked
      by the `downloaded_at` column.  The dataset is one record per reported date.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
  - name: vacunacion
    description: >
      The Puerto Rico Department of Health's daily COVID-19 vaccination datasets.
      We make one (or more) download per day and keep them all, as tracked by the
      `downloaded_at` column.  The dataset is one record per administered dose.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
