#
# Build ARM and Intel Docker images in AWS Codebuild.
#
version: 0.2

env:
    variables:
        IMAGE_REPO_NAME: covid-19-puerto-rico-downloader
    secrets-manager:
        DOCKER_HUB_USERNAME: covid-19-puerto-rico-docker-hub:username
        DOCKER_HUB_PASSWORD: covid-19-puerto-rico-docker-hub:password

phases:
    pre_build:
        commands:
            - set -euo pipefail
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - echo Logging in to Docker Hub...
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    build:
        commands:
            - set -euo pipefail
            - echo Build started on `date`
            - echo Building the Docker image...
            - echo IMAGE_REPO_NAME=${IMAGE_REPO_NAME?"IMAGE_REPO_NAME not set"}
            - echo IMAGE_TAG=${IMAGE_TAG?"IMAGE_TAG not set"}
            - cd downloader/
            - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    post_build:
        commands:
            - set -euo pipefail
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG