version: 2

models:
  - name: bioportal_tritemporal_agg
    description: '{{ doc("bioportal_tritemporal_agg") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - test_type
            - bulletin_date
            - collected_date
            - reported_date
            - received_date
      - dbt_utils.expression_is_true:
          expression: >
            positive_tests <= tests
    columns:
      - name: collected_date
        description: '{{ doc("collected_date") }}'
        tests:
          - not_null:
              severity: warn
          - dbt_utils.accepted_range:
              min_value: DATE '2020-03-01'
              max_value: bulletin_date
              inclusive: true
      - name: tests
        description: Count of the number test specimens.
      - name: positive_tests
        description: Count of the number of positive test specimens.

  - name: bioportal_collected_agg
    description: |
      Aggregate of `bioportal_tritemporal_agg` by test sample collection date.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - test_type
            - bulletin_date
            - collected_date

  - name: bioportal_reported_agg
    description: |
      Aggregate of `bioportal_tritemporal_agg` by lab report date.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - test_type
            - bulletin_date
            - reported_date

  - name: bioportal_received_agg
    description: |
      Aggregate of `bioportal_tritemporal_agg` by Bioportal result received date.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - test_type
            - bulletin_date
            - received_date
