version: 2

sources:
  - name: hhs
    schema: covid_hhs_sources
    loaded_at_field: date_parse(regexp_extract("$path", '202[012](\d{4})_(\d{4})'), '%Y%m%d_%H%i')
    tables:
      - name: reported_hospital_utilization_timeseries
        freshness:
          error_after: { count: 7, period: day }
      - name: reported_hospital_utilization
        freshness:
          error_after: { count: 1, period: day }
        loaded_at_field: date_parse(regexp_extract("$path", '202[012](\d{4})_(\d{4})'), '%Y%m%d_%H%i')
      - name: hospital_facilities
        identifier: reported_hospital_capacity_admissions_facility_level_weekly_average_timeseries
        freshness:
          error_after: { count: 7, period: day }
        loaded_at_field: date_parse(regexp_extract("$path", '202[012](\d{4})_(\d{4})'), '%Y%m%d_%H%i')
      - name: community_profile_report_county
        freshness:
          error_after: { count: 1, period: day }
      - name: diagnostic_lab_testing
        freshness:
          warn_after: { count: 1, period: day }
          error_after: { count: 36, period: hour }
      - name: vaccination_county_condensed_data_json
      - name: covid_tracking_csv