[postgres]
drivername = "postgresql"
host = "db"
port = "5432"
database = "postgres"
username = "postgres"
password = "password"

[athena]
region_name = "us-west-2"
schema_name = "covid19_puerto_rico_model"
s3_staging_dir = "s3://covid-19-puerto-rico-athena/"