name: Downloader Docker image

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
      - 'multiarch-downloader-github-action'
    paths:
      - '.github/workflows/BUILD_DOWNLOADER_IMAGE.yml'
      - 'downloader/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: csv2parquet
          platforms: linux/amd64,linux/arm64
          push: true
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: covid-19-puerto-rico-downloader
          tags: multiarch-downloader-github-action